### ISSUE TITLE
Cannot perform first run

### ISSUE THREAD

**Issue by mozo95** [blabla1337/skf-flask#614]
Hello,

We have deployed the docker image on-premise with a [nginx proxy](https://github.com/nginx-proxy/nginx-proxy). The only error docker logs gave us during the docker-compose up proccess, was with wrapper.sh - skf-angular.sh.
Below you can see the error.
![imagen](https://user-images.githubusercontent.com/57413382/85127076-0a0c3280-b22f-11ea-8a8f-6008045144c1.png)
Although this error ocurred, the container started successfully and the web application was accesible.
Nevertheless we couldn't perform the first run, as the first login feature did not respond to the "Create account" button.
![imagen](https://user-images.githubusercontent.com/57413382/85127589-ff9e6880-b22f-11ea-913a-866114fd23d6.png)

Below you can see the docker-compose file used.
```
version: '3'
services:
  nginx_proxy:
    image: jwilder/nginx-proxy
    container_name: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
    environment:
      - DEFAULT_HOST=git
    restart: always
skf_web:
    image: blabla1337/skf-flask
    container_name: skf_web
    environment:
      - ORIGIN=skf
      - JWT_SECRET=*****************
      - HTTPS=false
      - WEBSITES_PORT=80
      - VIRTUAL_HOST=skf
      - VIRTUAL_PORT=80
      - FRONTEND_URI=https://skf
      - SKF_API_URL=https://skf
        #- VIRTUAL_PROTO=https
    expose:
      - "80"
        #volumes:
            #- ./skf/db/db.sqlite:/skf-flask/skf/db/db.sqlite
    restart: always
```

We have also tested the deployment on Azure but we faced the same errors and behaviour.
Below you can see the docker-compose file used.
```
version: '3'
services:
   skf_web:
    image: blabla1337/skf-flask
    container_name: skf_web
    environment:
      - ORIGIN=skf
      - JWT_SECRET=****************
      - HTTPS=false
      - WEBSITES_PORT=80
      - WEBSITES_CONTAINER_START_TIME_LIMIT=800
      #- VIRTUAL_HOST=skf
      #- VIRTUAL_PORT=80
      #- FRONTEND_URI=https://skf
      #- SKF_API_URL=https://skf
      #- VIRTUAL_PROTO=https
    expose:
      - "80"
        #volumes:
            #- ./skf/db/db.sqlite:/skf-flask/skf/db/db.sqlite
    restart: always
```
