### ISSUE TITLE
Existing features missing 

### ISSUE THREAD

**Issue by timurozkul** [blabla1337/skf-flask#752]
I have tried running it locally on Docker. But it seems there are quite a few features missing such create project, update requirements, etc. I have logged in as admin following this link (https://skf.readme.io/docs/first-run), i assume i am admin but there is no indication. I have noticed that these features exist by looking at the source code but I cannot see them enabled on the application.

**Comment by timurozkul** [comment]
I noticed through Brup that the application does auto skip login (automatically redirects) so once a admin is created it auto logs you into the application but not as admin. In other words once the button on admin creation is clicked, the next thing that happens is you get logged in as non admin. I would say this is a bug because I am not able to stop this auto login "feature"

**Comment by lfservin** [comment]
you need to make a couple changes to your docker-compose script to avoid "auto-skipping" log in.

skf-angular has an attribute "environment". Here you want to set SKIP_LOGIN as:
```
- SKIP_LOGIN=skfprovider
```
it would then look like this:
```yaml
  skf-angular:
    container_name: skf-angular_container
    platform: linux/x86_64
    depends_on:
      - "rabbitmq"
      - "nginx"
      - "mysql"
    restart: always
    image: "blabla1337/skf-angular:4.0.2"
    environment:
      - FRONTEND_URI=http://localhost
      - SKIP_LOGIN=skfprovider

```
